on: workflow_dispatch
name: Application Deployment
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy SSH Key
      uses: steebchen/kubectl@v2.0.0
      with: # defaults to latest kubectl binary version
        config: ${{ secrets.KUBE_CONFIG }}
        command: apply -R -f ssh/
    - name: Verify Daemon Set
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG }}
        version: v1.21.0 # specify kubectl binary version explicitly
        command: get ds root-ssh-manager --namespace kube-system -o wide    
    - name: Verify Config Map
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG }}
        version: v1.21.0 # specify kubectl binary version explicitly
        command: get cm root-ssh-pubkeys --namespace kube-system